**Table of contents**<a id='toc0_'></a>    
- [Fluopy trials notebook](#toc1_)    
  - [Importing all modules](#toc1_1_)    
  - [Routine template](#toc1_2_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

# <a id='toc1_'></a>[Fluopy trials notebook](#toc0_)
This notebook is dedicated to test functionality of fluopy

## <a id='toc1_1_'></a>[Importing all modules](#toc0_)

In [16]:
import fluopy.fluorophores as fl
import fluopy.simulation as si
import fluopy.transitions as tr

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## <a id='toc1_2_'></a>[Routine template](#toc0_)

In [30]:
fluorophores = fl.construct_fluorophores(
    name="cy5_dna", distance=3, count=3, shape="square"
)
fluorophore_system = fl.FluorophoreSystem(fluorophores=fluorophores)

transitions = fluorophore_system.load_transitions(
    summarize=True,
    irradiance=5,
    wavelength=640,
    bleaching=True,
    energy_transfer=True,
    dstorm=True,
    dstorm_parameters={"reducing_agent": "mea", "concentration": 100, "ph": 7.5},
    energy_transfer_parameters={"overwrite": {"off": [1, 0.00001]}},
)
transition_set = tr.TransitionSet(transitions, fluorophore_system)
transition_set = transition_set.adjust_rates({8: 5e1})
transition_set.finalize()

transition_set.transition_df

                                                                     transition_type  \
Fluorophore                         identity
cy5_dna                             0                      TransitionType.EXCITATION
                                    1            TransitionType.FLUORESCENT_EMISSION
                                    2         TransitionType.INTERSYSTEM_CROSSING_ST
                                    3                   TransitionType.ISOMERIZATION
                                    4                        TransitionType.ADDUCT_T
                                    5                        TransitionType.ADDUCT_S
                                    6                      TransitionType.RAD_ESCAPE
                                    7                       TransitionType.RAD_RELAX
                                    8                TransitionType.PHOTOBLEACHING_1
                                    9               TransitionType.S1_S0_TRANSITIONS
                                    10              TransitionType.T1_S0_TRANSITIONS
                                    11             TransitionType.CIS_S0_TRANSITIONS
                                    12             TransitionType.OFF_S0_TRANSITIONS
D: cy5_dna, A: cy5_dna, dist: 3.0   13                     TransitionType.CIS_FRET_1
                                    14                     TransitionType.CIS_FRET_2
                                    15                     TransitionType.OFF_FRET_1
                                    16                     TransitionType.OFF_FRET_2
                                    17                           TransitionType.FRET
                                    18               TransitionType.S_S_ANNIHILATION
                                    19               TransitionType.S_T_ANNIHILATION
D: cy5_dna, A: cy5_dna, dist: 4.243 20                     TransitionType.CIS_FRET_1
                                    21                     TransitionType.CIS_FRET_2
                                    22                     TransitionType.OFF_FRET_1
                                    23                     TransitionType.OFF_FRET_2
                                    24                           TransitionType.FRET
                                    25               TransitionType.S_S_ANNIHILATION
                                    26               TransitionType.S_T_ANNIHILATION

                                             abbreviation       initial_state  \
Fluorophore                         identity
cy5_dna                             0                 EXC      SingleState.S0
                                    1                 FLU      SingleState.S1
                                    2              ISC_ST      SingleState.S1
                                    3                 ISO      SingleState.S1
                                    4              PET_TO      SingleState.T1
                                    5              PET_SO      SingleState.S1
                                    6              PET_TR      SingleState.T1
                                    7                 OXI       SingleState.R
                                    8                 BLE      SingleState.T1
                                    9             S1S0SUM      SingleState.S1
                                    10            T1S0SUM      SingleState.T1
                                    11           cisS0SUM     SingleState.cis
                                    12           OFFS0SUM     SingleState.OFF
D: cy5_dna, A: cy5_dna, dist: 3.0   13              CET_1  PairedState.S1_Cis
                                    14              CET_2  PairedState.S1_Cis
                                    15              OET_1  PairedState.S1_OFF
                                    16              OET_2  PairedState.S1_OFF
                                    17               FRET   PairedState.S1_S0
                                    18                SSA   PairedState.S1_S1
                                    19                STA   PairedState.S1_T1
D: cy5_dna, A: cy5_dna, dist: 4.243 20              CET_1  PairedState.S1_Cis
                                    21              CET_2  PairedState.S1_Cis
                                    22              OET_1  PairedState.S1_OFF
                                    23              OET_2  PairedState.S1_OFF
                                    24               FRET   PairedState.S1_S0
                                    25                SSA   PairedState.S1_S1
                                    26                STA   PairedState.S1_T1

                                                     final_state  \
Fluorophore                         identity
cy5_dna                             0             SingleState.S1
                                    1             SingleState.S0
                                    2             SingleState.T1
                                    3            SingleState.cis
                                    4            SingleState.OFF
                                    5            SingleState.OFF
                                    6              SingleState.R
                                    7             SingleState.S0
                                    8              SingleState.B
                                    9             SingleState.S0
                                    10            SingleState.S0
                                    11            SingleState.S0
                                    12            SingleState.S0
D: cy5_dna, A: cy5_dna, dist: 3.0   13        PairedState.S0_Cis
                                    14         PairedState.S0_S0
                                    15        PairedState.S0_OFF
                                    16         PairedState.S0_S0
                                    17         PairedState.S0_S1
                                    18         PairedState.S0_S1
                                    19         PairedState.S0_T1
D: cy5_dna, A: cy5_dna, dist: 4.243 20        PairedState.S0_Cis
                                    21         PairedState.S0_S0
                                    22        PairedState.S0_OFF
                                    23         PairedState.S0_S0
                                    24         PairedState.S0_S1
                                    25         PairedState.S0_S1
                                    26         PairedState.S0_T1

                                                      rate  photon  \
Fluorophore                         identity
cy5_dna                             0         1.453925e+07   False
                                    1         1.588235e+08    True
                                    2         8.300000e+05   False
                                    3         4.000000e+06   False
                                    4         3.065343e+02   False
                                    5         3.065343e+03   False
                                    6         3.065343e+03   False
                                    7         1.300000e+03   False
                                    8         5.000000e+01   False
                                    9         4.276471e+08   False
                                    10        3.115343e+05   False
                                    11        1.016550e+05   False
                                    12        1.066550e-01   False
D: cy5_dna, A: cy5_dna, dist: 3.0   13        1.177150e+11   False
                                    14        4.904790e+09   False
                                    15        5.010587e+09   False
                                    16        5.010637e+04   False
                                    17        6.398774e+10   False
                                    18        1.226198e+11   False
                                    19        3.614255e+10   False
D: cy5_dna, A: cy5_dna, dist: 4.243 20        1.470690e+10   False
                                    21        6.127873e+08   False
                                    22        6.260052e+08   False
                                    23        6.260115e+03   False
                                    24        7.994404e+09   False
                                    25        1.531968e+10   False
                                    26        4.515524e+09   False

                                                               fluorophore_ids  \
Fluorophore                         identity
cy5_dna                             0                                [0, 1, 2]
                                    1                                [0, 1, 2]
                                    2                                [0, 1, 2]
                                    3                                [0, 1, 2]
                                    4                                [0, 1, 2]
                                    5                                [0, 1, 2]
                                    6                                [0, 1, 2]
                                    7                                [0, 1, 2]
                                    8                                [0, 1, 2]
                                    9                                [0, 1, 2]
                                    10                               [0, 1, 2]
                                    11                               [0, 1, 2]
                                    12                               [0, 1, 2]
D: cy5_dna, A: cy5_dna, dist: 3.0   13        [(0, 1), (0, 2), (1, 0), (2, 0)]
                                    14        [(0, 1), (0, 2), (1, 0), (2, 0)]
                                    15        [(0, 1), (0, 2), (1, 0), (2, 0)]
                                    16        [(0, 1), (0, 2), (1, 0), (2, 0)]
                                    17        [(0, 1), (0, 2), (1, 0), (2, 0)]
                                    18        [(0, 1), (0, 2), (1, 0), (2, 0)]
                                    19        [(0, 1), (0, 2), (1, 0), (2, 0)]
D: cy5_dna, A: cy5_dna, dist: 4.243 20                        [(1, 2), (2, 1)]
                                    21                        [(1, 2), (2, 1)]
                                    22                        [(1, 2), (2, 1)]
                                    23                        [(1, 2), (2, 1)]
                                    24                        [(1, 2), (2, 1)]
                                    25                        [(1, 2), (2, 1)]
                                    26                        [(1, 2), (2, 1)]

                                              absorbing
Fluorophore                         identity
cy5_dna                             0             False
                                    1             False
                                    2             False
                                    3             False
                                    4             False
                                    5             False
                                    6             False
                                    7             False
                                    8              True
                                    9             False
                                    10            False
                                    11            False
                                    12            False
D: cy5_dna, A: cy5_dna, dist: 3.0   13            False
                                    14            False
                                    15            False
                                    16            False
                                    17            False
                                    18            False
                                    19            False
D: cy5_dna, A: cy5_dna, dist: 4.243 20            False
                                    21            False
                                    22            False
                                    23            False
                                    24            False
                                    25            False
                                    26            False

In [31]:
transition_set.combined_state_transitions_df

,initial_state,final_state,fluorophore_ids,abbreviation,transition_id,rate,photon
id,,,,,,,
0,"(0, 0, 0)","(0, 0, 1)",[2],EXC,0,1.453925e+07,False
1,"(0, 0, 0)","(0, 1, 0)",[1],EXC,0,1.453925e+07,False
2,"(0, 0, 0)","(1, 0, 0)",[0],EXC,0,1.453925e+07,False
3,"(0, 0, 1)","(0, 1, 1)",[1],EXC,0,1.453925e+07,False
4,"(0, 0, 1)","(1, 0, 1)",[0],EXC,0,1.453925e+07,False
...,...,...,...,...,...,...,...
2200,"(7, 3, 1)","(7, 3, 0)","[2, 1]",STA,26,4.515524e+09,False
2201,"(9, 1, 3)","(9, 0, 3)","[1, 2]",STA,26,4.515524e+09,False
2202,"(9, 3, 1)","(9, 3, 0)","[2, 1]",STA,26,4.515524e+09,False
2203,"(5, 1, 3)","(5, 0, 3)","[1, 2]",STA,26,4.515524e+09,False
2204,"(5, 3, 1)","(5, 3, 0)","[2, 1]",STA,26,4.515524e+09,False

In [32]:
sim = si.Simulation(transition_set)
sim.run(size=4e5, kap_sq_var=True, seed=42, use_memmap=None, accuracy=11)

Floating point precision error warning:
 The higher limit of smallest increment with a probability of 1.00e-03 is 1.91e-15.
 This was estimated using the highest possible rate which occurs for example in state combination [1, 1, 1].
 Everything drawn below this number will be rounded to zero starting somewhere between 1.00e+01 - 1.00e+02.

Index([1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920,
       ...
       2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203, 2204],
      dtype='int64', name='id', length=294)